### ISSUE TITLE
more scaling options for gnome desktop

### ISSUE THREAD

**Issue by Joe-Public** [batchworksde/iksdp_desktop#27]
- with a 4K display 100% scaling is quite small, 200% too big
- also with lower resolutions options like 125% and 150% would be helpful

![image](https://github.com/user-attachments/assets/f0a595b4-5709-45e0-a9e3-3977d756c18d)

**Comment by birkb** [comment]
- https://wiki.archlinux.org/title/HiDPI#Desktop_environments
- https://gist.github.com/hallettj/3075e5fee24ce62dafef9c87ec353630
- https://wiki.gnome.org/Initiatives/FracionalScaling

**Comment by Joe-Public** [comment]
see [5b3805d](https://github.com/batchworksde/iksdp_desktop/commit/5b3805d95eb4d5fc9a2721530660ba7b57fcf452)
