### ISSUE TITLE
reasonable default configuration

### ISSUE THREAD

**Issue by Joe-Public** [batchworksde/iksdp_desktop#29]
prevent configuration dialog when booting without persistent flash drive

![image](https://github.com/user-attachments/assets/6c83cc2a-bec6-4d3a-9a7f-1e415c326ae5)

**Comment by birkb** [comment]
[sysconf.tar.gz](http://iksdp.pfadfinderzentrum.org/sysconf.tar.gz) contains some good examples

**Comment by Joe-Public** [comment]
see [d326d81](https://github.com/batchworksde/iksdp_desktop/commit/d326d81)
