### ISSUE TITLE
add gnome-shell extensions

### ISSUE THREAD

**Issue by birkb** [batchworksde/iksdp_desktop#4]
- [ ] [gnome-shell-extensions](https://packages.debian.org/bookworm/gnome-shell-extensions)
- [ ] [Dash2Dock Animated](https://extensions.gnome.org/extension/4994/dash2dock-lite/)
- [ ] [No overview at start-up](https://extensions.gnome.org/extension/4099/no-overview/)
- [ ] [Gtk4 Desktop Icons NG (DING)](https://extensions.gnome.org/extension/5263/gtk4-desktop-icons-ng-ding/)
- [ ] [ArcMenu](https://extensions.gnome.org/extension/3628/arcmenu/)
- [ ] [Apps Menu](https://extensions.gnome.org/extension/6/applications-menu/)

**Comment by Joe-Public** [comment]
see [bca00a4](https://github.com/batchworksde/iksdp_desktop/commit/bca00a4f0487ac4446f3b0fb36ee797adaa9686e)
